version: '3'

services:
  node:
    image: zelhtar/ubuntu-nginx-php-mysql
    container_name: sellerProduct
    volumes:
        - .:/app/
    ports:
        - "80:80"
        - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: '12341234'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12341234'